### ISSUE TITLE
Trusted coin: mind the latest API break

### ISSUE THREAD

**Issue by darosior** [fiatjaf/lightningd-gjson-rpc#3]
Hi,

We broke the API for Bitcoin backends in https://github.com/ElementsProject/lightning/pull/3570 (`estimatefees`).
The doc for the new interface is available [here](https://github.com/ElementsProject/lightning/pull/3620), otherwise you can check https://github.com/lightningd/plugins/pull/95 for the design choices I made for Esplora (and the reason).

**Comment by fiatjaf** [comment]
Thank you very much. This will make my life easier.
